export const STATUS_ENUM_TO_LABEL = {
    New: "New",
    Open: "Open",
    InActive: "Inactive",
    Close: "Closed (Cust Pick Up)",
    Cancel: "Cancel (Cust Pick Up)",
    Active: "Active",
    Monitor: "Monitor",
    Pending_Customer_Action: "Pending Customer Action",
    Quote_Requested: "Quote Requested",
    Pending_Follow_Up: "Pending Follow Up",
    Pending_Order: "Pending Order",
    Escalated: "Escalated",
    Quote_Approved: "Quote Approved",
    Quote_Rejected: "Quote Rejected",
    Pending_Quote: "Pending Quote",
    NEW_AssignFD: "New Assign To FD",
    NEW_AssignCE: "New Assign To CE",
    NEW_AssignLeader: "New Assign To Leader",
    NEW_AssignAPO: "New Assign To APO",
    NEW_AssignPS: "New Assign To PS",
    NEW_AssignCM: "New Assign To CM",
    AssignFD: "Assign To FD",
    AssignCE: "Assign To CE",
    AssignAPO: "Assign To APO",
    AssignLeader: "Assign To Leader",
    AssignPS: "Assign To PS",
    AssignCM: "Assign To CM",
    NEW_POPDoc: "New Needed POP Document",
    NEW_Warranty: "New Warranty (Warranty Proses)",
    PartRequest: "Part Request",
    PartRequestLog: "Part Order Logistic",
    PartOrder: "Part Request Logistic",
    PartAvailable: "Part Available",
    RepairProgress: "Repair Progress",
    FinishRepair: "Finish Repair",
    CancelRepair: "Cancel Repair",
    Closed: "Closed",
    Cancelled: "Cancelled",
    Void: "Void",
    Reschedule: "Reschedule",
    DOAPartReturn: "DOA Part Return",
    Customer_Delay: "Customer Delay"
};

export const statusEnumToLabelWO = {
    OPEN_UNSCHEDULED: "Open - Unscheduled",
    OPEN_SCHEDULED: "Open - Scheduled",
    REPAIR_PROGRESS: "Open - In Progress",
    OPEN_COMPLETED: "Open - Completed",
    CLOSED_POSTED: "Closed - Posted",
    CLOSED_CANCELLED: "Closed - Cancelled"
  };


